function resultsDir = getResultsDir(opticalElements, inertPigments, overlap,fixationMeanDuration, microFixationGain, osType)
    resultsDir = fullfile(...
        sprintf('OpticalElements_%s_InertPigments_%s', opticalElements, inertPigments), ...
        sprintf('Overlap%2.2f_Fixation%dms_MicrofixationGain%2.1f', overlap, fixationMeanDuration, microFixationGain), ...
        sprintf('%s', osType) ...
    );
end