function resultsDir = getResultsDir(opticalElements, inertPigments, overlap,fixationMeanDuration, microFixationGain, mosaicSize, reconstructedStimulusSpatialResolutionInMicrons, osType)
    resultsDir = fullfile(...
        sprintf('OpticalElements_%s_InertPigments_%s', opticalElements, inertPigments), ...
        sprintf('Overlap%2.2f_Fixation%dms_MicrofixationGain%2.1f_MosaicSize%dx%d_ReconstructedStimulusSpatialResolution_%3.1fMicrons', overlap, fixationMeanDuration, microFixationGain, mosaicSize(1), mosaicSize(2), reconstructedStimulusSpatialResolutionInMicrons), ...
        sprintf('%s', osType) ...
    );
end