function sceneSet = sceneSetWithName(sceneSetName)
        
    switch (sceneSetName)
        
        case 'harvard_machester_upenn'
            sceneSet = cat(2, sceneNamesForHarvardDataBase(), sceneNamesForManchesterDataBase(), sceneNamesForUPennDataBase());
            
        case 'harvard'
            sceneSet = sceneNamesForHarvardDataBase();
            
        case 'upenn'
            sceneSet = sceneNamesForUPennDataBase();
            
        case 'harvard_manchester'
            sceneSet = cat(2, sceneNamesForHarvardDataBase(), sceneNamesForManchesterDataBase());
            
        case 'manchester'
            sceneSet = sceneNamesForManchesterDataBase();
 
        otherwise
            error('Unknown scene set name: ''%s''.\n', sceneSetName);
    end
end

function sceneSet = sceneNamesForHarvardDataBase()
    s = {...
            'img1', 'img2', 'img4', 'img6', ...
            'imga1', 'imga2', 'imga4', 'imga5', 'imga6', 'imga7', 'imga8', ...
            'imgb1', 'imgb2', 'imgb3', 'imgb5', 'imgb6', ...
            'imgc1', 'imgc2', 'imgc3', 'imgc4', 'imgc5', 'imgc6', 'imgc7', 'imgc8', 'imgc9', ...
            'imgd0', 'imgd1', 'imgd2', 'imgd3', 'imgd4', 'imgd5', 'imgd6', 'imgd7', 'imgd8', 'imgd9', ...
            'imge0', 'imge1', 'imge2', 'imge3', 'imge4', 'imge5', 'imge6', 'imge7', ...
            'imgf1', 'imgf2', 'imgf4', 'imgf5', 'imgf6', 'imgf7', 'imgf8', ...
            'imgg0', 'imgg2', 'imgg5', 'imgg8', 'imgg9', ...
            'imgh0', 'imgh1', 'imgh2', 'imgh3' ...
    };
        
    tmp = {};
    for k = 1:numel(s)
        tmp{numel(tmp)+1} = {'harvard_database', s{k}};    
    end
    sceneSet = tmp;
end


    
function sceneSet = sceneNamesForManchesterDataBase()
    sceneSet = {...
                {'manchester_database', 'scene1'} ...
                {'manchester_database', 'scene2'} ...
                {'manchester_database', 'scene3'} ...
                {'manchester_database', 'scene6'} ...
                {'manchester_database', 'scene7'} ...
                {'manchester_database', 'scene8'} ... 
                {'manchester_database', 'scene4'} ...
     };
end


function sceneSet = sceneNamesForUPennDataBase()
    sceneSet = {...
                {'penn_database', 'BearFruitGrayR'} ...
                {'penn_database', 'BearFruitGrayG'} ...
                {'penn_database', 'BearFruitGrayB'} ...
                {'penn_database', 'BearFruitGrayY'} ...
    };
end

