function batchImportHyperSpectralImages

    %% Get our project toolbox on the path
    myDir = fileparts(mfilename('fullpath'));
    pathDir = fullfile(myDir,'..','Toolbox','');
    AddToMatlabPathDynamically(pathDir);
   
    % set to true if you want to see the generated isetbio data
    showIsetbioData = true;
    
    whichDataBase = 'manchester_database';
    
    %whichDataBase = 'harvard_database';
    
    
    switch (whichDataBase)
        
        case 'harvard_database'
            
            % subset containing 50 (both outdoors and indoors) images under daylight ilumination
            whichSubset   = 'CZ_hsdb';
    
    
            applyMotionMask = false;
            set1HarvardUniv = { ...
%                 struct('databaseName', whichDataBase, 'subsetDirectory', whichSubset, 'sceneName','img1',  'applyMotionMask', false, 'clipLuminance', 4000,  'gammaValue', 1.7, 'outlineWidth', 1, 'showIsetbioData', showIsetbioData) ...
%                 struct('databaseName', whichDataBase, 'subsetDirectory', whichSubset, 'sceneName','img2',  'applyMotionMask', false, 'clipLuminance', 4000,  'gammaValue', 1.7, 'outlineWidth', 1, 'showIsetbioData', showIsetbioData) ...
%                 struct('databaseName', whichDataBase, 'subsetDirectory', whichSubset, 'sceneName','imga1', 'applyMotionMask', false, 'clipLuminance', 4000,  'gammaValue', 1.7, 'outlineWidth', 1, 'showIsetbioData', showIsetbioData) ...
%                 struct('databaseName', whichDataBase, 'subsetDirectory', whichSubset, 'sceneName','imga2', 'applyMotionMask', false, 'clipLuminance', 4000,  'gammaValue', 1.7, 'outlineWidth', 1, 'showIsetbioData', showIsetbioData) ...
%                 struct('databaseName', whichDataBase, 'subsetDirectory', whichSubset, 'sceneName','imga5', 'applyMotionMask', false, 'clipLuminance', 4000,  'gammaValue', 1.7, 'outlineWidth', 1, 'showIsetbioData', showIsetbioData) ...
%                 struct('databaseName', whichDataBase, 'subsetDirectory', whichSubset, 'sceneName','imga6', 'applyMotionMask', false, 'clipLuminance', 4000,  'gammaValue', 1.7, 'outlineWidth', 1, 'showIsetbioData', showIsetbioData) ...
%                 struct('databaseName', whichDataBase, 'subsetDirectory', whichSubset, 'sceneName','imga7', 'applyMotionMask', false, 'clipLuminance', 4000,  'gammaValue', 1.7, 'outlineWidth', 1, 'showIsetbioData', showIsetbioData) ...
%                 struct('databaseName', whichDataBase, 'subsetDirectory', whichSubset, 'sceneName','imgb1', 'applyMotionMask', false, 'clipLuminance', 4000,  'gammaValue', 1.7, 'outlineWidth', 1, 'showIsetbioData', showIsetbioData) ...
%                 struct('databaseName', whichDataBase, 'subsetDirectory', whichSubset, 'sceneName','imgb2', 'applyMotionMask', false, 'clipLuminance', 4000,  'gammaValue', 1.7, 'outlineWidth', 1, 'showIsetbioData', showIsetbioData) ...
%                 struct('databaseName', whichDataBase, 'subsetDirectory', whichSubset, 'sceneName','imgb3', 'applyMotionMask', false, 'clipLuminance', 4000,  'gammaValue', 1.7, 'outlineWidth', 1, 'showIsetbioData', showIsetbioData) ...
%                 struct('databaseName', whichDataBase, 'subsetDirectory', whichSubset, 'sceneName','imgb4', 'applyMotionMask', false, 'clipLuminance', 4000,  'gammaValue', 1.7, 'outlineWidth', 1, 'showIsetbioData', showIsetbioData) ...
%                 struct('databaseName', whichDataBase, 'subsetDirectory', whichSubset, 'sceneName','imgb5', 'applyMotionMask', false, 'clipLuminance', 4000,  'gammaValue', 1.7, 'outlineWidth', 1, 'showIsetbioData', showIsetbioData) ...
%                 struct('databaseName', whichDataBase, 'subsetDirectory', whichSubset, 'sceneName','imgb6', 'applyMotionMask', false, 'clipLuminance', 4000,  'gammaValue', 1.7, 'outlineWidth', 1, 'showIsetbioData', showIsetbioData) ...
%                  struct('databaseName', whichDataBase, 'subsetDirectory', whichSubset, 'sceneName','imgb7', 'applyMotionMask', false, 'clipLuminance', 4000,  'gammaValue', 1.7, 'outlineWidth', 1, 'showIsetbioData', showIsetbioData) ...
%                  struct('databaseName', whichDataBase, 'subsetDirectory', whichSubset, 'sceneName','imgb8', 'applyMotionMask', false, 'clipLuminance', 4000,  'gammaValue', 1.7, 'outlineWidth', 1, 'showIsetbioData', showIsetbioData) ...
%                 struct('databaseName', whichDataBase, 'subsetDirectory', whichSubset, 'sceneName','imgb9', 'applyMotionMask', false, 'clipLuminance', 4000,  'gammaValue', 1.7, 'outlineWidth', 1, 'showIsetbioData', showIsetbioData) ...
%                 struct('databaseName', whichDataBase, 'subsetDirectory', whichSubset, 'sceneName','imgc1', 'applyMotionMask', false, 'clipLuminance', 4000,  'gammaValue', 1.7, 'outlineWidth', 1, 'showIsetbioData', showIsetbioData) ...
%                 struct('databaseName', whichDataBase, 'subsetDirectory', whichSubset, 'sceneName','imgc2', 'applyMotionMask', false, 'clipLuminance', 4000,  'gammaValue', 1.7, 'outlineWidth', 1, 'showIsetbioData', showIsetbioData) ...
%                 struct('databaseName', whichDataBase, 'subsetDirectory', whichSubset, 'sceneName','imgc4', 'applyMotionMask', false, 'clipLuminance', 4000,  'gammaValue', 1.7, 'outlineWidth', 1, 'showIsetbioData', showIsetbioData) ...
%                 struct('databaseName', whichDataBase, 'subsetDirectory', whichSubset, 'sceneName','imgc5', 'applyMotionMask', false, 'clipLuminance', 4000,  'gammaValue', 1.7, 'outlineWidth', 1, 'showIsetbioData', showIsetbioData) ...
%                 struct('databaseName', whichDataBase, 'subsetDirectory', whichSubset, 'sceneName','imgc7', 'applyMotionMask', false, 'clipLuminance', 4000,  'gammaValue', 1.7, 'outlineWidth', 1, 'showIsetbioData', showIsetbioData) ...
%                 struct('databaseName', whichDataBase, 'subsetDirectory', whichSubset, 'sceneName','imgc8', 'applyMotionMask', false, 'clipLuminance', 4000,  'gammaValue', 1.7, 'outlineWidth', 1, 'showIsetbioData', showIsetbioData) ...
%                  struct('databaseName', whichDataBase, 'subsetDirectory', whichSubset, 'sceneName','imgc9', 'applyMotionMask', false, 'clipLuminance', 4000,  'gammaValue', 1.7, 'outlineWidth', 1, 'showIsetbioData', showIsetbioData) ...
%                 struct('databaseName', whichDataBase, 'subsetDirectory', whichSubset, 'sceneName','imgd2', 'applyMotionMask', false, 'clipLuminance', 4000,  'gammaValue', 1.7, 'outlineWidth', 1, 'showIsetbioData', showIsetbioData) ...
%                 struct('databaseName', whichDataBase, 'subsetDirectory', whichSubset, 'sceneName','imgd3', 'applyMotionMask', false, 'clipLuminance', 4000,  'gammaValue', 1.7, 'outlineWidth', 1, 'showIsetbioData', showIsetbioData) ...
%                 struct('databaseName', whichDataBase, 'subsetDirectory', whichSubset, 'sceneName','imgd4', 'applyMotionMask', false, 'clipLuminance', 4000,  'gammaValue', 1.7, 'outlineWidth', 1, 'showIsetbioData', showIsetbioData) ...
%                 struct('databaseName', whichDataBase, 'subsetDirectory', whichSubset, 'sceneName','imgd7', 'applyMotionMask', false, 'clipLuminance', 4000,  'gammaValue', 1.7, 'outlineWidth', 1, 'showIsetbioData', showIsetbioData) ...
%                 struct('databaseName', whichDataBase, 'subsetDirectory', whichSubset, 'sceneName','imgd8', 'applyMotionMask', false, 'clipLuminance', 4000,  'gammaValue', 1.7, 'outlineWidth', 1, 'showIsetbioData', showIsetbioData) ...
%                 struct('databaseName', whichDataBase, 'subsetDirectory', whichSubset, 'sceneName','imgd9', 'applyMotionMask', false, 'clipLuminance', 4000,  'gammaValue', 1.7, 'outlineWidth', 1, 'showIsetbioData', showIsetbioData) ...
%                  struct('databaseName', whichDataBase, 'subsetDirectory', whichSubset, 'sceneName','imge0', 'applyMotionMask', false, 'clipLuminance', 4000,  'gammaValue', 1.7, 'outlineWidth', 1, 'showIsetbioData', showIsetbioData) ...
%                  struct('databaseName', whichDataBase, 'subsetDirectory', whichSubset, 'sceneName','imge1', 'applyMotionMask', false, 'clipLuminance', 4000,  'gammaValue', 1.7, 'outlineWidth', 1, 'showIsetbioData', showIsetbioData) ...
%                  struct('databaseName', whichDataBase, 'subsetDirectory', whichSubset, 'sceneName','imge2', 'applyMotionMask', false, 'clipLuminance', 4000,  'gammaValue', 1.7, 'outlineWidth', 1, 'showIsetbioData', showIsetbioData) ...
%                 struct('databaseName', whichDataBase, 'subsetDirectory', whichSubset, 'sceneName','imge3', 'applyMotionMask', false, 'clipLuminance', 4000,  'gammaValue', 1.7, 'outlineWidth', 1, 'showIsetbioData', showIsetbioData) ...
%                 struct('databaseName', whichDataBase, 'subsetDirectory', whichSubset, 'sceneName','imge4', 'applyMotionMask', false, 'clipLuminance', 4000,  'gammaValue', 1.7, 'outlineWidth', 1, 'showIsetbioData', showIsetbioData) ...
%                 struct('databaseName', whichDataBase, 'subsetDirectory', whichSubset, 'sceneName','imge5', 'applyMotionMask', false, 'clipLuminance', 4000,  'gammaValue', 1.7, 'outlineWidth', 1, 'showIsetbioData', showIsetbioData) ...
%                 struct('databaseName', whichDataBase, 'subsetDirectory', whichSubset, 'sceneName','imge6', 'applyMotionMask', false, 'clipLuminance', 4000,  'gammaValue', 1.7, 'outlineWidth', 1, 'showIsetbioData', showIsetbioData) ...
%                  struct('databaseName', whichDataBase, 'subsetDirectory', whichSubset, 'sceneName','imge7', 'applyMotionMask', false, 'clipLuminance', 4000,  'gammaValue', 1.7, 'outlineWidth', 1, 'showIsetbioData', showIsetbioData) ...
%                 struct('databaseName', whichDataBase, 'subsetDirectory', whichSubset, 'sceneName','imgf1', 'applyMotionMask', false, 'clipLuminance', 4000,  'gammaValue', 1.7, 'outlineWidth', 1, 'showIsetbioData', showIsetbioData) ...
%                 struct('databaseName', whichDataBase, 'subsetDirectory', whichSubset, 'sceneName','imgf2', 'applyMotionMask', false, 'clipLuminance', 4000,  'gammaValue', 1.7, 'outlineWidth', 1, 'showIsetbioData', showIsetbioData) ...
%                  struct('databaseName', whichDataBase, 'subsetDirectory', whichSubset, 'sceneName','imgf3', 'applyMotionMask', false, 'clipLuminance', 4000,  'gammaValue', 1.7, 'outlineWidth', 1, 'showIsetbioData', showIsetbioData) ...
%                 struct('databaseName', whichDataBase, 'subsetDirectory', whichSubset, 'sceneName','imgf4', 'applyMotionMask', false, 'clipLuminance', 4000,  'gammaValue', 1.7, 'outlineWidth', 1, 'showIsetbioData', showIsetbioData) ...
%                 struct('databaseName', whichDataBase, 'subsetDirectory', whichSubset, 'sceneName','imgf5', 'applyMotionMask', false, 'clipLuminance', 4000,  'gammaValue', 1.7, 'outlineWidth', 1, 'showIsetbioData', showIsetbioData) ...
%                 struct('databaseName', whichDataBase, 'subsetDirectory', whichSubset, 'sceneName','imgf6', 'applyMotionMask', false, 'clipLuminance', 4000,  'gammaValue', 1.7, 'outlineWidth', 1, 'showIsetbioData', showIsetbioData) ...
%                 struct('databaseName', whichDataBase, 'subsetDirectory', whichSubset, 'sceneName','imgf7', 'applyMotionMask', false, 'clipLuminance', 4000,  'gammaValue', 1.7, 'outlineWidth', 1, 'showIsetbioData', showIsetbioData) ...
%                  struct('databaseName', whichDataBase, 'subsetDirectory', whichSubset, 'sceneName','imgf8', 'applyMotionMask', false, 'clipLuminance', 4000,  'gammaValue', 1.7, 'outlineWidth', 1, 'showIsetbioData', showIsetbioData) ...
%                 struct('databaseName', whichDataBase, 'subsetDirectory', whichSubset, 'sceneName','imgh0', 'applyMotionMask', false, 'clipLuminance', 4000,  'gammaValue', 1.7, 'outlineWidth', 1, 'showIsetbioData', showIsetbioData) ...
%                 struct('databaseName', whichDataBase, 'subsetDirectory', whichSubset, 'sceneName','imgh1', 'applyMotionMask', false, 'clipLuminance', 4000,  'gammaValue', 1.7, 'outlineWidth', 1, 'showIsetbioData', showIsetbioData) ...
%                 struct('databaseName', whichDataBase, 'subsetDirectory', whichSubset, 'sceneName','imgh2', 'applyMotionMask', false, 'clipLuminance', 4000,  'gammaValue', 1.7, 'outlineWidth', 1, 'showIsetbioData', showIsetbioData) ...
%                 struct('databaseName', whichDataBase, 'subsetDirectory', whichSubset, 'sceneName','imgh3', 'applyMotionMask', false, 'clipLuminance', 4000,  'gammaValue', 1.7, 'outlineWidth', 1, 'showIsetbioData', showIsetbioData) ...  
            };
            
            % subset containing 25 images under artificial and mixed
            % illumination. These have been color - balanced by me
            % (nicolas) based on either the existing Xrite color balance
            % card or objects of white appearance (if a Xrite card does not
            % exist in the scene). The area used for white balancing is
            % outlined in red-blue.
            whichSubset   = 'CZ_hsdbi';
            
            set2HarvardUniv = { ...
%                 struct('databaseName', whichDataBase, 'subsetDirectory', whichSubset, 'sceneName','img3', 'applyMotionMask', false, 'clipLuminance', 4000,  'gammaValue', 1.7, 'outlineWidth', 1, 'showIsetbioData', showIsetbioData) ...
%                 struct('databaseName', whichDataBase, 'subsetDirectory', whichSubset, 'sceneName','img4', 'applyMotionMask', false, 'clipLuminance', 4000,  'gammaValue', 1.7, 'outlineWidth', 1, 'showIsetbioData', showIsetbioData) ...
%                 struct('databaseName', whichDataBase, 'subsetDirectory', whichSubset, 'sceneName','img5', 'applyMotionMask', false, 'clipLuminance', 4000,  'gammaValue', 1.7, 'outlineWidth', 1, 'showIsetbioData', showIsetbioData) ...
%                 struct('databaseName', whichDataBase, 'subsetDirectory', whichSubset, 'sceneName','img6', 'applyMotionMask', false, 'clipLuminance', 4000,  'gammaValue', 1.7, 'outlineWidth', 1, 'showIsetbioData', showIsetbioData) ...
%                 struct('databaseName', whichDataBase, 'subsetDirectory', whichSubset, 'sceneName','imga3', 'applyMotionMask', false, 'clipLuminance', 4000,  'gammaValue', 1.7, 'outlineWidth', 1, 'showIsetbioData', showIsetbioData) ...
%                 struct('databaseName', whichDataBase, 'subsetDirectory', whichSubset, 'sceneName','imga4', 'applyMotionMask', false, 'clipLuminance', 4000,  'gammaValue', 1.7, 'outlineWidth', 1, 'showIsetbioData', showIsetbioData) ...
%                 struct('databaseName', whichDataBase, 'subsetDirectory', whichSubset, 'sceneName','imga8', 'applyMotionMask', false, 'clipLuminance', 4000,  'gammaValue', 1.7, 'outlineWidth', 1, 'showIsetbioData', showIsetbioData) ...
%                 struct('databaseName', whichDataBase, 'subsetDirectory', whichSubset, 'sceneName','imgc3', 'applyMotionMask', false, 'clipLuminance', 4000,  'gammaValue', 1.7, 'outlineWidth', 1, 'showIsetbioData', showIsetbioData) ...
%                 struct('databaseName', whichDataBase, 'subsetDirectory', whichSubset, 'sceneName','imgc6', 'applyMotionMask', false, 'clipLuminance', 4000,  'gammaValue', 1.7, 'outlineWidth', 1, 'showIsetbioData', showIsetbioData) ...
%                 struct('databaseName', whichDataBase, 'subsetDirectory', whichSubset, 'sceneName','imgd0', 'applyMotionMask', false, 'clipLuminance', 4000,  'gammaValue', 1.7, 'outlineWidth', 1, 'showIsetbioData', showIsetbioData) ...
%                 struct('databaseName', whichDataBase, 'subsetDirectory', whichSubset, 'sceneName','imgd1', 'applyMotionMask', false, 'clipLuminance', 4000,  'gammaValue', 1.7, 'outlineWidth', 1, 'showIsetbioData', showIsetbioData) ...                struct('databaseName', whichDataBase, 'subsetDirectory', whichSubset, 'sceneName','imgd5', 'applyMotionMask', applyMotionMask, 'clipLuminance', 4000,  'gammaValue', 1.7, 'outlineWidth', 1, 'showIsetbioData', showIsetbioData) ...
%                 struct('databaseName', whichDataBase, 'subsetDirectory', whichSubset, 'sceneName','imgd6', 'applyMotionMask', false, 'clipLuminance', 4000,  'gammaValue', 1.7, 'outlineWidth', 1, 'showIsetbioData', showIsetbioData) ...
%                 struct('databaseName', whichDataBase, 'subsetDirectory', whichSubset, 'sceneName','imgg0', 'applyMotionMask', false, 'clipLuminance', 4000,  'gammaValue', 1.7, 'outlineWidth', 1, 'showIsetbioData', showIsetbioData) ...
%                 struct('databaseName', whichDataBase, 'subsetDirectory', whichSubset, 'sceneName','imgg1', 'applyMotionMask', false, 'clipLuminance', 4000,  'gammaValue', 1.7, 'outlineWidth', 1, 'showIsetbioData', showIsetbioData) ...
%                 struct('databaseName', whichDataBase, 'subsetDirectory', whichSubset, 'sceneName','imgg2', 'applyMotionMask', false, 'clipLuminance', 4000,  'gammaValue', 1.7, 'outlineWidth', 1, 'showIsetbioData', showIsetbioData) ...
%                 struct('databaseName', whichDataBase, 'subsetDirectory', whichSubset, 'sceneName','imgg3', 'applyMotionMask', false, 'clipLuminance', 4000,  'gammaValue', 1.7, 'outlineWidth', 1, 'showIsetbioData', showIsetbioData) ...
%                 struct('databaseName', whichDataBase, 'subsetDirectory', whichSubset, 'sceneName','imgg4', 'applyMotionMask', false, 'clipLuminance', 4000,  'gammaValue', 1.7, 'outlineWidth', 1, 'showIsetbioData', showIsetbioData) ...
%                 struct('databaseName', whichDataBase, 'subsetDirectory', whichSubset, 'sceneName','imgg5', 'applyMotionMask', false, 'clipLuminance', 4000,  'gammaValue', 1.7, 'outlineWidth', 1, 'showIsetbioData', showIsetbioData) ...
%                 struct('databaseName', whichDataBase, 'subsetDirectory', whichSubset, 'sceneName','imgg6', 'applyMotionMask', false, 'clipLuminance', 4000,  'gammaValue', 1.7, 'outlineWidth', 1, 'showIsetbioData', showIsetbioData) ...
%                 struct('databaseName', whichDataBase, 'subsetDirectory', whichSubset, 'sceneName','imgg7', 'applyMotionMask', false, 'clipLuminance', 4000,  'gammaValue', 1.7, 'outlineWidth', 1, 'showIsetbioData', showIsetbioData) ...
%                 struct('databaseName', whichDataBase, 'subsetDirectory', whichSubset, 'sceneName','imgg8', 'applyMotionMask', false, 'clipLuminance', 4000,  'gammaValue', 1.7, 'outlineWidth', 1, 'showIsetbioData', showIsetbioData) ...
%                 struct('databaseName', whichDataBase, 'subsetDirectory', whichSubset, 'sceneName','imgg9', 'applyMotionMask', false, 'clipLuminance', 4000,  'gammaValue', 1.7, 'outlineWidth', 1, 'showIsetbioData', showIsetbioData) ...
%                 struct('databaseName', whichDataBase, 'subsetDirectory', whichSubset, 'sceneName','imgh4', 'applyMotionMask', false, 'clipLuminance', 4000,  'gammaValue', 1.7, 'outlineWidth', 1, 'showIsetbioData', showIsetbioData) ...
%                 struct('databaseName', whichDataBase, 'subsetDirectory', whichSubset, 'sceneName','imgh5', 'applyMotionMask', false, 'clipLuminance', 4000,  'gammaValue', 1.7, 'outlineWidth', 1, 'showIsetbioData', showIsetbioData) ...
%                 struct('databaseName', whichDataBase, 'subsetDirectory', whichSubset, 'sceneName','imgh6', 'applyMotionMask', false, 'clipLuminance', 4000,  'gammaValue', 1.7, 'outlineWidth', 1, 'showIsetbioData', showIsetbioData) ...
%                 struct('databaseName', whichDataBase, 'subsetDirectory', whichSubset, 'sceneName','imgh7', 'applyMotionMask', false, 'clipLuminance', 4000,  'gammaValue', 1.7, 'outlineWidth', 1, 'showIsetbioData', showIsetbioData) ...
            };
       
            
            
    
            % Full set
            set = {set1HarvardUniv{:} set2HarvardUniv{:}};
        
        case 'manchester_database'
        % Scenes with recorded information regarding geometry and illuminant.
        set1MancesterUniv = { ...
            struct('databaseName', 'manchester_database', 'sceneName','scene1', 'clipLuminance', 4000,  'gammaValue', 1.7, 'outlineWidth', 1, 'showIsetbioData', showIsetbioData) ...
            struct('databaseName', 'manchester_database', 'sceneName','scene2', 'clipLuminance', 4000,  'gammaValue', 1.7, 'outlineWidth', 1, 'showIsetbioData', showIsetbioData) ...
            struct('databaseName', 'manchester_database', 'sceneName','scene3', 'clipLuminance', 4000,  'gammaValue', 1.7, 'outlineWidth', 1, 'showIsetbioData', showIsetbioData) ...
            struct('databaseName', 'manchester_database', 'sceneName','scene4', 'clipLuminance',12000,  'gammaValue', 1.7, 'outlineWidth', 2, 'showIsetbioData', showIsetbioData) ...
            struct('databaseName', 'manchester_database', 'sceneName','scene5', 'clipLuminance',12000,  'gammaValue', 1.7, 'outlineWidth', 2, 'showIsetbioData', showIsetbioData) ...  % this will be skipped because of discrepancy b/n number of spectral bands in reflectance/illuminant
            struct('databaseName', 'manchester_database', 'sceneName','scene6', 'clipLuminance',14000,  'gammaValue', 1.7, 'outlineWidth', 2, 'showIsetbioData', showIsetbioData) ...
            struct('databaseName', 'manchester_database', 'sceneName','scene7', 'clipLuminance',8000,  'gammaValue', 1.7, 'outlineWidth', 2, 'showIsetbioData', showIsetbioData) ...
            struct('databaseName', 'manchester_database', 'sceneName','scene8', 'clipLuminance',8000,  'gammaValue', 1.7, 'outlineWidth', 1, 'showIsetbioData', showIsetbioData) ...
             };

        % Scenes with missing (but filled-in, by Nicolas) information regarding geometry and illuminant.
        set2MancesterUniv = { ...
  %           struct('databaseName', 'manchester_database', 'sceneName','scene9',  'clipLuminance', 4000,  'gammaValue', 1.7, 'outlineWidth', 1, 'showIsetbioData', showIsetbioData) ...
  %           struct('databaseName', 'manchester_database', 'sceneName','scene10', 'clipLuminance', 4000,  'gammaValue', 1.7, 'outlineWidth', 1, 'showIsetbioData', showIsetbioData) ...
  %           struct('databaseName', 'manchester_database', 'sceneName','scene11', 'clipLuminance', 5000,  'gammaValue', 1.7, 'outlineWidth', 1, 'showIsetbioData', showIsetbioData) ...
  %           struct('databaseName', 'manchester_database', 'sceneName','scene12', 'clipLuminance', 5000,  'gammaValue', 1.7, 'outlineWidth', 1, 'showIsetbioData', showIsetbioData) ...
  %           struct('databaseName', 'manchester_database', 'sceneName','scene13', 'clipLuminance', 5000,  'gammaValue', 1.7, 'outlineWidth', 1, 'showIsetbioData', showIsetbioData) ...
 %            struct('databaseName', 'manchester_database', 'sceneName','scene14', 'clipLuminance', 9000,  'gammaValue', 1.7, 'outlineWidth', 1, 'showIsetbioData', showIsetbioData) ...
 %            struct('databaseName', 'manchester_database', 'sceneName','scene15', 'clipLuminance', 12000,  'gammaValue', 1.7, 'outlineWidth', 1, 'showIsetbioData', showIsetbioData) ...
 %            struct('databaseName', 'manchester_database', 'sceneName','scene16', 'clipLuminance', 12000,  'gammaValue', 1.7, 'outlineWidth', 1, 'showIsetbioData', showIsetbioData) ...
        };

        % Full set
        set = {set1MancesterUniv{:} set2MancesterUniv{:}};
        
    end
    
    
    
    exportIsetbioSceneObject = true;
    % Start the batch import and process
    for k = 1:numel(set)
        s = set{k};
        fprintf('\n<strong>--------------------------------------------------------------------------------------------</strong>\n');
        fprintf('<strong>%2d. Importing data files for scene ''%s'' of database ''%s''.</strong>\n', k, s.sceneName, s.databaseName);
        fprintf('<strong>--------------------------------------------------------------------------------------------</strong>\n');
        importHyperSpectralImage(s, exportIsetbioSceneObject);
    end
end







