function [Ctrain, CtrainPrediction, Ctest, CtestPrediction, SVDvarianceExplained, svdIndex] = retrievePerformanceData(sceneSetName, decodingDataDir, computeSVDbasedLowRankFiltersAndPredictions)
    fprintf('\nLoading in-sample prediction data ...');
    fileName = fullfile(decodingDataDir, sprintf('%s_inSamplePrediction.mat', sceneSetName));
    load(fileName, 'Ctrain', 'CtrainPrediction', 'originalTrainingStimulusSize', 'expParams');
  
    if (computeSVDbasedLowRankFiltersAndPredictions)
        load(fileName, 'CtrainPredictionSVDbased', 'SVDbasedLowRankFilterVariancesExplained');
        svdIndex = core.promptUserForChoiceFromSelectionOfChoices('Select desired variance explained for the reconstruction filters', SVDbasedLowRankFilterVariancesExplained);
        if (numel(svdIndex)>1)
            return;
        end
        SVDvarianceExplained = SVDbasedLowRankFilterVariancesExplained(svdIndex);
        CtrainPrediction = squeeze(CtrainPredictionSVDbased(svdIndex,:, :));
    end
        
    fprintf('\nLoading out-of-sample prediction data ...');
    fileName = fullfile(decodingDataDir, sprintf('%s_outOfSamplePrediction.mat', sceneSetName));
    load(fileName, 'Ctest', 'CtestPrediction', 'originalTestingStimulusSize');
    if (computeSVDbasedLowRankFiltersAndPredictions)
        load(fileName, 'CtestPredictionSVDbased', 'SVDbasedLowRankFilterVariancesExplained');
        CtestPrediction = squeeze(CtestPredictionSVDbased(svdIndex,:, :));
    end
    
    
    CtrainPrediction  = ...
        decoder.reformatStimulusSequence('FromDesignMatrixFormat', ...
            decoder.shiftStimulusSequence(CtrainPrediction, expParams.decoderParams), ...
            originalTrainingStimulusSize ...
        );
  
    Ctrain  = ...
        decoder.reformatStimulusSequence('FromDesignMatrixFormat', ...
            decoder.shiftStimulusSequence(Ctrain, expParams.decoderParams), ...
            originalTrainingStimulusSize ...
        );
    
    CtestPrediction  = ...
        decoder.reformatStimulusSequence('FromDesignMatrixFormat', ...
            decoder.shiftStimulusSequence(CtestPrediction, expParams.decoderParams), ...
            originalTestingStimulusSize ...
        );
  
    Ctest  = ...
        decoder.reformatStimulusSequence('FromDesignMatrixFormat', ...
            decoder.shiftStimulusSequence(Ctest, expParams.decoderParams), ...
            originalTestingStimulusSize ...
        );
    
end
