function runSimulation

    databaseName = 'manchester_database';
    sceneName = 'scene3';
    verbosity = 10;
    
    % Instantiate a new sceneProcessor
    sceneProcessor = ISETbioSceneProcessor(databaseName, sceneName, verbosity);
    
    % Compute optical image
    % We may specify custom optics params
%     opticsParamsStruct = struct('name', 'human', ...);
%     sceneProcessor.computeOpticalImage(...
%         'opticsParams', opticsParamsStruct, ...
%         'forceRecompute', true ...
%         'visualizeResults', true
%     );

    Speak('Hit enter for optical image');
    pause;
    % or use default optics
    sceneProcessor.computeOpticalImage(...
        'forceRecompute', false, ...
        'visualizeResultsAsIsetbioWindows', true, ...
        'visualizeResultsAsImages', false ...
    );

    % We may specify custon sensor params
    
    
    sensorParamsStruct = struct(...
                'name', 'humanLMS', ...
                'FOVdegrees', 1.0, ...
                'coneIntegrationTime', 0.050, ...
                'eyeMovementParams', struct( ...
                    'sampleTime', 5.0/1000.0 ...  % sample every 5 milliseconds
                ) ...
    );



    Speak('Hit enter for sensor image');
    pause;
    sceneProcessor.computeSensorImage(...
        'forceRecompute', true, ...
        'sensorParams', sensorParamsStruct , ...
        'visualizeResultsAsIsetbioWindows', true, ...
        'visualizeResultsAsImages', true ...
    );

end

