function runSimulation

    databaseName = 'manchester_database';
    sceneName = 'scene3';
    verbosity = 10;
    
    % Instantiate a new sceneProcessor
    sceneProcessor = ISETbioSceneProcessor(databaseName, sceneName, verbosity);
    
    % Compute optical image
    % We may specify custom optics params
%     opticsParamsStruct = struct('name', 'human', ...);
%     sceneProcessor.computeOpticalImage(...
%         'opticsParams', opticsParamsStruct, ...
%         'forceRecompute', true ...
%         'visualizeResults', true
%     );

    Speak('Hit enter for optical image');
    pause;
    % or use default optics
    sceneProcessor.computeOpticalImage(...
        'forceRecompute', false, ...
        'visualizeResultsAsIsetbioWindows', true, ...
        'visualizeResultsAsImages', false ...
    );

    % We may specify custon sensor params
    sensorParamsStruct = struct(...
                'name', 'human', ...
                'coneIntegrationTime', 0.050 ...
    );

    Speak('Hit enter for sensor image');
    pause;
    sceneProcessor.computeSensorImage(...
        'forceRecompute', false, ...
        'visualizeResultsAsIsetbioWindows', true, ...
        'visualizeResultsAsImages', true ...
    );

end

