function generateReferenceObjectDataStruct(obj)

    % Assemble sourceDirectory path
    sourceDir = fullfile(getpref('HyperSpectralImageComputations', 'originalDataBaseDir'), obj.sceneData.database);
    
    switch (obj.sceneData.name)
        
        case 'scene4'   
            % Spectral data for reference paint material
            % Load the reference paint spectral data ('ref_n7')
            ref_n7 = [];
            load(fullfile(sourceDir, obj.sceneData.name, obj.sceneData.referencePaintFileName));
            if (isempty(ref_n7))
                error('Data file does not contain the expected ''ref_n7'' field.');
            end
            obj.referenceObjectData = struct(...
                'spectroRadiometerReadings', struct( ...
                    'xChroma',      0.351, ...     % 
                    'yChroma',      0.363, ...
                    'Yluma',        8751,  ...     % cd/m2
                    'CCT',          4827   ...     % deg kelvin
                    ), ...
                 'paintMaterial', struct( ...
                    'name',   'Munsell N7 matt grey', ...
                    'wave', ref_n7(:,1),...
                    'spd',  ref_n7(:,2) ...
                 ), ...
                 'geometry', struct( ...
                    'shape',            'sphere', ...
                    'distanceToCamera', 1.4, ...         % meters
                    'sizeInMeters',     3.75/100.0, ...  % for this scene, the reported size is the ball diameter
                    'sizeInPixels',     167, ...         % estimated manually from the picture
                    'roiXYpos',         [83 981], ...    % pixels
                    'roiSize',          [10 10] ...      % pixels
                 ), ...
                 'info', ['Recorded in the Gualtar campus of University of Minho, Portugal, on 31 July 2002 at 17:40, ' ...
                        'under direct sunlight and blue sky. Ambient temperature: 29 C. ' ...
                        'Camera aperture: f/22, focus: 38, zoom set to maximum giving a focal length of 75 mm'] ...
            );
        
    end  % switch
end